---
  - name: Update System
    shell: "{{ item }}"
    with_items:
      - "{{ update_commands }}"
  - name: Install Packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ default_apps }}"
...