---
required_packages:
  - java-11-openjdk-devel
  - policycoreutils-python
  - vim
  - wget
firewall_commands:
  - firewall-cmd --add-port=5524/tcp --permanent
  - firewall-cmd --add-port=5525/tcp --permanent
  - firewall-cmd --add-port=5526/tcp --permanent
  - firewall-cmd --add-port=5526/tcp --permanent
  - firewall-cmd --add-port=5528/tcp --permanent
  - firewall-cmd --add-port=5529/tcp --permanent
  - firewall-cmd --add-port=5530/tcp --permanent
  - firewall-cmd --reload
  - systemctl enable logstash
...