---
# Install Dependicies:
- name: Install Package(s)
  yum:
    name: "{{ required_packages }}"
    state: present

# Add the Elasticsearch apt repo. For higher versions 8+ of the stack - use '8.x-prerelease':
- name: Adding Elasticsearch repo
  yum_repository:
    name: ELK
    description: ELK YUM repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

# Install Logstash
- name: Install elasticsearch with yum
  yum:
    name: elasticsearch
    state: present
   
# Configure Elasticsearch:

- name: Set Cluster Name
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   line: 'cluster.name: nazerick-logs'

- name: Set Node Name
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   line: 'node.name: Master-01'

- name: Set Memory Lock
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#bootstrap.memory_lock: true'
   line: 'bootstrap.memory_lock: true'

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 10.8.5.35'

- name: Setting Seed Hosts
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#discovery.seed_hosts: ["host1", "host2"]'
   line: 'discovery.seed_hosts: ["127.0.0.1"]'

- name: Set initial Master Node
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.initial_master_nodes: ["node-1", "node-2"]'
   line: 'cluster.initial_master_nodes: ["Master-01"]'

- name: Set minimum jvm heap size
  lineinfile:
   destfile: /etc/elasticsearch/jvm.options
   regexp: '-Xms1g'
   line: '-Xms8g'

- name: Set maximum jvm heap size
  lineinfile:
   destfile: /etc/elasticsearch/jvm.options
   regexp: '-Xmx1g'
   line: '-Xmx8g'

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'

# Restart Daemon
- name: Starting Elasticsearch
  shell: "{{ item }}"
  with_items:
    - "{{ service_commands }}"

# Starting Elasticsearch
- name: Starting Elasticsearch
  systemd:
   name: elasticsearch
   state: started

# Finish Config:
- name: Configuring firewall & Enabeling services
  shell: "{{ item }}"
  with_items:
    - "{{ final_commands }}"
...