---
# Install Dependicies:
- name: Install Required Package(s)
  yum:
    name: "{{ required_packages }}"
    state: present

# Add the Elasticsearch apt repo. For higher versions 8+ of the stack - use '8.x-prerelease':
- name: Adding Elasticsearch repo
  yum_repository:
    name: ELK
    description: ELK YUM repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

# Install Logstash
- name: Install elasticsearch with yum
  yum:
    name: elasticsearch
    state: present
   
# Configure Elasticsearch:

- name: Set Cluster Name
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name: my-application'
   line: 'cluster.name: nazerick-logs'

- name: Set Node Name
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#node.name: node-1'
   line: 'node.name: Master-01'


- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: {{ elasticsearch_ip }}'

- name: Updating the port in config file 
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'

- name: Set Memory Lock
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: '#bootstrap.memory_lock: true'
   line: 'bootstrap.memory_lock: true'

- name: Disable Bootstrap Checks
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   insertafter: '# --------------------------------- Discovery ----------------------------------'
   line: 'discovery.type: single-node'

- name: Set minimum jvm heap size
  lineinfile:
   destfile: /etc/elasticsearch/jvm.options
   regexp: '-Xms1g'
   line: '-Xms8g'

- name: Set maximum jvm heap size
  lineinfile:
   destfile: /etc/elasticsearch/jvm.options
   regexp: '-Xmx1g'
   line: '-Xmx8g'

# Restart Daemon
- name: Configuring Elasticsearch Service
  shell: "{{ item }}"
  with_items:
    - "{{ service_commands }}"

# Starting Elasticsearch
- name: Starting Elasticsearch
  systemd:
   name: elasticsearch
   state: started

# Finish Config:
- name: Configuring firewall & Enabeling services
  shell: "{{ item }}"
  with_items:
    - "{{ final_commands }}"
...