---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  become: yes
  become_user: root
  roles:
  - { role: ./roles/System-Builds/elasticsearch }
  - { role: ./roles/System-Builds/kibana }
  - { role: ./roles/System-Builds/metricbeat }