---
- name: Installing RasberryPi Machine(s) Default Apps
  hosts: rasberrypi
  become: yes
  roles:
    - ./roles/initial-configuration/rasberrypi

- name: Installing Centos Machine(s) Default Apps
  hosts: allcentos
  become: yes
  roles:
    - ./roles/initial-configuration/centos

- name: Installing Ubuntu Machine(s) Default Apps
  hosts: allubuntu
  become: yes
  roles:
    - ./roles/initial-configuration/ubuntu
...