---
update_commands:
  - sudo yum install -y epel-release
  - sudo yum update -y
default_apps:
  - vim
  - cockpit
  - wget
  - rsync
  - tcpdump
  - rsyslog
  - htop
  - sssd
  - realmd
  - oddjob
  - oddjob-mkhomedir
  - adcli
  - samba-common
  - samba-common-tools
  - krb5-workstation
  - openldap-clients
  - policycoreutils-python
...