---
- name: Initializing RasberryPi Machine(s)
  hosts: raspi
  roles:
    - ./roles/initial-configuration/raspi

- name: Initializing Centos 7 Machine(s)
  hosts: centos7
  roles:
    - ./roles/initial-configuration/centos7

- name: Initializing Centos 8 Machine(s)
  hosts: centos8
  roles:
    - ./roles/initial-configuration/centos8
...